### PR TITLE
Blockly integration as alternate Editor mode.

### PR DESCRIPTION
**Pull request by fuglaro**
Includes blocks for all of the ThumbyAPI.
Blockly Editors launched separately from the Widgets menu. HelloBlockly default code shows when opening empty Blockly Editors. OPEN PYTHON button opens new MicroPython Editor with generated code. Integration into BitmapBuilder's Import/Export.
Sprite images show on [load sprite] blocks.
Not directly compatible with IMPORT SPRITE.
Editor mode picker for when opening webpage for the first time or after
  a Hard Reset (select between Blockly or MicroPython for the first editor.
'New Tab' (MicroPython) and 'New Blockly Tab' on the Editor's File menu.
  New Tab opens the normal code editor.
Includes Copy and Paste support across editor tabs. Automatically gives Blockly editors a Path for ease of use.

### CODE REVIEW

**Comment by masonova1** [comment]
Two notes from the office:

Is there any way to open a file back up as a Blockly-edited file after saving to Thumby? Would be a nice feature to be able to seamlessly switch between editors on the same file, but it seems as though we can only go from Blockly to Python.

It's not clear that the "export to PC" option generates _blockly_ code, not Python code. We can talk new file extensions to clear this up.

**Comment by fuglaro** [comment]
Thank you for looking!!!

Yeah, it's only one way, unfortunately. The only option would be to inject
the block data inside the python, or alongside it for the Thumby. The block
data is just a big JSON blob. You could detect it and yank it back out
easily enoug.

I was thinking file.blocks as an extension when it Exports to PC. I didn't
make a decision on that.

Currently the Editor Path for Blockly files must end in .py otherwise the
Emulator will not run it, but we could change the emulator to automatically
change the path name from .blocks to .py. The same would have to happen
when making the .py for saving to the Thumby.

I guess if we injected the JSON blocks into the py, everything would be
cleaner?

I'm happy to play with the injected JSON idea if you all like that.

**Comment by fuglaro** [comment]
Oooh, I could hash the python to know if the injected blocks were out if
date...

**Comment by masonova1** [comment]
Is there any way to do the Python generation on-the-fly with the Thumby? I'm thinking that memory constraints will get in the way, but there also might be a way to do the parsing smartly and sequentially without storing all of anything at once. That way, the Python doesn't actually have to be maintained in unison with the Blockly source, and it only has to be cached and sometimes regenerated when the Blockly file changes. Again, this may be a far more involved task for the Thumby than I'm presently imagining. If it is just a matter of keeping a `blocklyLauncher.py` or something, then that may be our answer.

**Comment by fuglaro** [comment]
I'm theory you could do it, but the block data interpretor, the python code
generator and the framework for it is all currently implemented in
JavaScript. So a rather large chunk of that would have to be rewritten. I'm
not actually sure how hard it would be.

**Comment by masonova1** [comment]
The best answer I've got right now involves just storing both on the Thumby and using different file extensions, and throwing in some guardrails to try and stop people from editing their python.

**Comment by fuglaro** [comment]
Yeah, that sounds good to me. The editor can see if both files are there
and warn about editing the python.

**Comment by masonova1** [comment]
I did find this: https://github.com/kashifrazzaqui/json-streamer

Although it's only a parser; We'd still need to do all of the translation heavy-lifting.

**Comment by fuglaro** [comment]
I'll try to prep the two stored files with guardrails idea on the weekend.
Then we have a reasonable baseline for anything better.

**Comment by fuglaro** [comment]
I've pushed a couple of changes that now:
* Save to PC as .blocks
* Saves to Thumby as both .py and .blocks
* Watermarks generated python code with #### !!!! BLOCKLY EXPORT !!!! #### at the start and end.
* Prevents saving to Thumby from MicroPython editors with the watermark detected anywhere in the file.

**Comment by masonova1** [comment]
This works pretty well, so far! Just a few more nitpicks:

* When a Blockly file is open in the editor, it shows `.py` as the extension instead of `.blocks`
* I like this approach to protecting `.py` file edits. Can we strengthen the blockly export detection? I was thinking the filenames should be compared inside the save directory, e.g. a Python file with `#### !!!! BLOCKLY EXPORT !!!! ####` would trigger the warning iff. there is a `.blocks` file in the same directory with the same name.

**Comment by fuglaro** [comment]
Hi Mason,

Thank you for taking a look at these changes.

For the Blockly editors showing the .py as the extension instead of the
.blocks, this was intentional for some quirky reasons. I can go in any
direction but I need help on making the decision. Currently, all the
editors have a nice feature where it won't let you open two editors with
the same path. I presume this is so there is no confusion if editors with
the same path are sent to the Thumby or the Emulator. Since all .blockly
files get resolved to .py files (and need to so they can get imported),
there would be a chance of collision when doing things like emulating. My
current logic is based on the idea that the path shows what the file *will
resolve to*, but it leaves things quite quirky when you save to your PC. I
personally like this because then it makes sense if you import files
resolved from blockly editors, from other python files.

I could change it to show .blocks, but where it detects for multiple
editors with the same path, should I ignore the potential collisions? Or
should I update all the checks for collisions to detect for .blocks and .py
collisions specifically, and the raise a different alert that says that
.blocks files can not have the same path and name as a .py file?

For the strengthening of the Blockly export detection, I really like this
idea! I just wan't to check if you mean for saving to the Thumby, or
exporting to PC, as I don't know if it is possible to check on the PC.
Browsers like to block websites from scanning peoples' filesystems. I
haven't double checked this.

I actually wanted to do the check on the Thumby when I made those changes,
but wasn't sure about the right way to do it. Is it okay if I do the
following?
*When saving to thumby, if it is a python editor, and #### !!!! BLOCKLY
EXPORT !!!! #### is in the text, then poll a new REPL.checkFileExists
function, and if the .blocks equivalent file exists, alert.*
I think I have to query via repl, and I'm hoping that waiting for the
additional query of the thumby is okay because I only do it if the text
also exists.

Thanks!

**Comment by masonova1** [comment]
Hey!

In my opinion, a given editor tab should show the name of the file you are editing, not what it will save to. It may make sense to open up the exported `.py` in the editor after the fact, though. Whatever approach we take, it should have some consistency between  "save to thumby" and "save to PC" functionalities. To put that another way, as a user, I would expect the _exact same file, set of files, or directory/archive of files_ to be saved by both buttons.

Editor path collisions shouldn't be allowed to happen in general; We should check for any files that are already open, whether they are Python, Blockly, or otherwise. Right now, If we "pull the rug out" from the emulator and re-export/edit the Python file mid-emulation, the emulator simply carries on executing what it has. I don't think this behavior needs to change.

> [...] raise a different alert that says that
> .blocks files can not have the same path and name as a .py file?

I'm not exactly sure what you meant by the alert -- I thought we stored the `.py` and `.blocks` in the same directory under the same name to begin with?

Lastly, I was thinking we can add a "do not edit the Python" warning _when exporting_ the `.py` file?

I can't see any functional problem with the approach you outlined in the last paragraph. Keep me posted, and thanks for your hard work!

**Comment by fuglaro** [comment]
Amazing! Thank you for all of this! I'm excited to tackle it to try and get
it right.

My question around the alert is, should I allow two editors to be open at
the same time with paths like this:
myGame.blocks
myGame.py
Or should this say you can't have two editors open with the same name? Its
a bit of a nuance because saving the .blocks file to the thumby (ill fix
the download to match), also generates the .py file.
Given what you have said, it sounds like I should detect that collision. It
get that in and we can see it in action but let me know if you don't agree.

Thank you for the clarity on everything else. I really like the direction
you are driving this!

**Comment by fuglaro** [comment]
I've committed all that and pushed to my github pages.
Note to self: Still need to go through any documentation ThumbyWebsite screengrabs and update now that editor tabs are renamed from HelloBlockly.py to HelloBlockly.blocks, and any relevant changes in the docs themselves.

**Comment by fuglaro** [comment]
I've updated the docs PR to match: https://github.com/TinyCircuits/Thumby-Website/pull/10

**Comment by Lennevia** [comment]
Started playing around with things and it looks like the recent change for the .blocks extension broke something :0!
Here's the error I get when trying to emulate the getting started example block:
import-error

**Comment by fuglaro** [comment]
Thank you Lennevia! I completely missed that! You were 100% right with what you thought the problem is. My apologies for missing that and for the sloppy testing on my part!
I have pushed a fix now and done a very quick test and it is looking better now.
Thank you also for taking a look!

**Comment by jmtinycircuits** [comment]
Pressing the key combination ctrl-s doesn't seem to save the Blockly file like it does for a normal text/code editor, instead it tries to save the web page.

**Comment by jmtinycircuits** [comment]
I'll take your word for the saving working. Merging in 10 minutes.

**Comment by fuglaro** [comment]
Thanks @jmtinycircuits! I've made an update that supports that now in a similar way to the normal text/code editor. Thanks for checking that!

**Pull request merged**
