### PR TITLE
Add -2 color and key to several graphic functions for inverting pixels

### PR DESCRIPTION
**Pull request by Xyvir**
I used -2 for parameter instead of making new function names as:

it's drop-in feature for existing games 
it's similar to -1 meaning draw both pixels in blit (-1 = draw both 1 and 0, -2 = XOR 1)
it probably wont' throw exceptions if a game using this feature happens to gets ran on an older API version
it's terse
Color parameters 2 and 3 are already reserved for greyscale library.

Let me know what you think, thanks!

-Xyvir

### CODE REVIEW

**Comment by Xyvir** [comment]
Here is an idea of what it looks like: (For drawfilledrectangle)

https://user-images.githubusercontent.com/23508213/213077946-8c587da2-5332-4f20-bbfc-ba2f818f010b.mp4

**Comment by Xyvir** [comment]
Yeah looks like I goofed the emulator one, I'll get that fixed

**Comment by Xyvir** [comment]
@ace-dent 

I fixed the Emulator thumbGraphics.py now, shouldn't have any of those unintended line deletions.

I understand the argument for keeping the API as lean as possible and anyone that wanted this functionality could add it themselives via their own library.

My argument for the inclusion of this feature is that I wanted added (surely I can't be alone in this)

And I wanted to have it available for anyone else who wanted it but doesn't feel comfortable trying edit, modifying or adding libraries to the API themselves.

Thanks for the input.

**Comment by ace-dent** [comment]
@Xyvir - thanks for checking.
Re. the utility... with so much onboard storage, I think most users would just create an inverted sprite... but perhaps that's just me! Will leave it to TC team to debate :-)

**Comment by Xyvir** [comment]
You can do stuff with inverse sprites like here

https://media.discordapp.net/attachments/898292174410612787/1066360594309070898/20230121_081455.mp4

**Comment by Xyvir** [comment]
https://user-images.githubusercontent.com/23508213/214141700-0c1b4dad-1cd1-45fd-bfd9-29aca14922e8.mp4

**Comment by masonova1** [comment]
Magic numbers in general are our concern regarding this change. It may be worth discussing named color constants (`thumby.display.black`, `thumby.display.white`, `thumby.display.inverse`, etc) for these purposes, even if they just evaluate to magic numbers under the hood; I'm not sure there's any way out of this without ample documentation.

**Comment by Xyvir** [comment]
I'm good with that, I can update the pr to include the names constants if you'd like.

I don't disagree that this would require updating the documentation, I'm willing to make a PR for that as well assuming this PR gets tentative approval.

What do recommend for -1 in regards to draw sprite?

opaque?
black-white

**Comment by Xyvir** [comment]
That was a mislcick, message inc

**Comment by Xyvir** [comment]
I'm good to add named constants to avoid veering off into magic number land.

I only picked -2 cause -1 was already kind of a 'magic number' to mean no key for the sprite function, and I wanted to follow suit.

I talked things over with the greyscale guys as they are already using named constants for colors in their library.

here's where we ended up proposing:
```
thumby.display.BLACK = 0
thumby.display.WHITE = 1
thumby.display.TOGGLE = -2
thumby.display.NOKEY = -1

If you like that I can get those constants added to the PR, then I will also work on getting a PR to update the documentation as well.

Just let me know what you think, thanks!

-Tyler

**Comment by Xyvir** [comment]
Would also cover this PR as well

https://github.com/TinyCircuits/Thumby-Website/issues/6

**Comment by Xyvir** [comment]
@masonova1 

I've added named constants as you had recommended, please let me know your thoughts, thanks.

-Tyler

**Comment by jmtinycircuits** [comment]
It would probably be more clear in the source if you used those new named constants instead of the values them selves.

For example, this https://github.com/TinyCircuits/TinyCircuits-Thumby-Code-Editor/pull/72/files#diff-ce5408123d4675289688d5a8f84e4712cffbcb907cf301f83fa4c87445b0f7afR108 would turn from `elif int(color)==int(-2):` to `elif int(color)==int(self.TOGGLE):`

**Comment by Xyvir** [comment]
@jmtinycircuits 
Sounds good.

To clarify, Would you like me to update the existing conditionals for one and zero as well, to reference the named constants black and white

I should probably just do them all while I'm at it

**Comment by jmtinycircuits** [comment]
That would make sense, if you don't mind.

**Comment by Xyvir** [comment]
No problem at all!

**Comment by Xyvir** [comment]
@jmtinycircuits 

Ok I've got the conditionals updated with the named constants now. I've briefly tested this fork on my thumby and I didn't run into any issues.

Please give it a look over, thanks.

**Comment by jmtinycircuits** [comment]
I gave it a look again but will need to bring this up to the rest of the team one more time. Changes to the API, at this point, need to be solidly implemented and worth it if it's going to be shipped out on production Thumbys.

**Comment by jmtinycircuits** [comment]
Is the addition of `thumby.display.NOKEY` really needed? Doesn't seem to be used anywhere.

**Comment by Xyvir** [comment]
Its used in `blit()` , `blitWithMask()`, (and by association `sprite()`
 if it makes it to the final 'color' else, as is currently the case in the API

https://github.com/Xyvir/ESPBoy-TinyCircuits-Thumby-Code-Editor/blob/master/ThumbyGames/lib/thumbyGraphics.py#L366

My use of -2 was originally inspired by use of -1 as seen in the doccos below.

I assumed this was done intentionally as a catch-all, so that any other integer could be used as a 'sentinal value' instead of just -1.

if not I could make this conditional if you'd prefer.

Or add a comment clarifying what's happening.

Just let me know.

-Tyler

**Comment by Xyvir** [comment]
I added a couple of comments where it matters; my thinking is that the documentation would need to be updated as it explicitly mentions -1 as accepted value for the 'key' parameter (although this value is never explicit in the code itself, `blit()` takes anything else besides 0, 1, and now -2 to draw all pixels).

 So it made sense to me for this 'magic number' to have it's own named constant as well.

I made it -1 to stay consistent with the existing documentation.
 
 Let me know if you have any questions, thanks.

-Tyler

**Comment by jmtinycircuits** [comment]
I talked with the team a little more and we had some concerns that will withhold this from being accepted for now.

1. The percentage size/line increase went up a little more than 10%. We want the API to be as small as possible to ensure import time is as fast as possible (while still being somewhat readable)
2. As I said earlier, we always have worries about changing the core API at this point. This code will end up being shipped to customers and we already have an API that's been working for around a year.
3. If grayscale somehow gets integrated the in future, this will make the code even larger because of the extra conditions.
4. Lots of changes to documentation would need to be made and verified

As you said, this could be implemented in a per-game basis as well.

Sorry to have made you waste your time. At least you were able to refine your code as mush as possible for your own use.

I'll be closing this for now but would re-open it if a strong argument can be made.

**Comment by Xyvir** [comment]
No waste of time at all! I appreciate the consideration and thoughtful criticisms.

It's been a learning experience for me for sure.

Thanks for the thumby and the great community it's fostered.

-Tyler

**Pull request closed without merging**
